/* tslint:disable */
/* eslint-disable */
/**
 * Clash Bot Service
 * # Welcome to Clash Bot!   Where all of your League of Legends Clash scheduling needs are met!  ## Purpose  Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.  ## Disclaimer  Clash-Bot is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or  anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games  are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The base necessary Tournament details
 * @export
 * @interface BaseTournament
 */
export interface BaseTournament {
    /**
     * The name of the Tournament.
     * @type {string}
     * @memberof BaseTournament
     */
    tournamentName?: string;
    /**
     * The day number of the Tournament. [1-4]
     * @type {string}
     * @memberof BaseTournament
     */
    tournamentDay?: string;
}

/**
 * Check if a given object implements the BaseTournament interface.
 */
export function instanceOfBaseTournament(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BaseTournamentFromJSON(json: any): BaseTournament {
    return BaseTournamentFromJSONTyped(json, false);
}

export function BaseTournamentFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseTournament {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tournamentName': !exists(json, 'tournamentName') ? undefined : json['tournamentName'],
        'tournamentDay': !exists(json, 'tournamentDay') ? undefined : json['tournamentDay'],
    };
}

export function BaseTournamentToJSON(value?: BaseTournament | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tournamentName': value.tournamentName,
        'tournamentDay': value.tournamentDay,
    };
}

