/* tslint:disable */
/* eslint-disable */
/**
 * Clash Bot Service
 * # Welcome to Clash Bot!   Where all of your League of Legends Clash scheduling needs are met!  ## Purpose  Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.  ## Disclaimer  Clash-Bot is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or  anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games  are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A record listing details on a League of Legends champion
 * @export
 * @interface Champion
 */
export interface Champion {
    /**
     * 
     * @type {string}
     * @memberof Champion
     */
    name?: string;
}

/**
 * Check if a given object implements the Champion interface.
 */
export function instanceOfChampion(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChampionFromJSON(json: any): Champion {
    return ChampionFromJSONTyped(json, false);
}

export function ChampionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Champion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function ChampionToJSON(value?: Champion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

