/* tslint:disable */
/* eslint-disable */
/**
 * Clash Bot Service
 * # Welcome to Clash Bot!   Where all of your League of Legends Clash scheduling needs are met!  ## Purpose  Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.  ## Disclaimer  Clash-Bot is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or  anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games  are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Champion } from './Champion';
import {
    ChampionFromJSON,
    ChampionFromJSONTyped,
    ChampionToJSON,
} from './Champion';

/**
 * A list of League of Legends champions and their details
 * @export
 * @interface Champions
 */
export interface Champions {
    /**
     * 
     * @type {Array<Champion>}
     * @memberof Champions
     */
    champions?: Array<Champion>;
}

/**
 * Check if a given object implements the Champions interface.
 */
export function instanceOfChampions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChampionsFromJSON(json: any): Champions {
    return ChampionsFromJSONTyped(json, false);
}

export function ChampionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Champions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'champions': !exists(json, 'champions') ? undefined : ((json['champions'] as Array<any>).map(ChampionFromJSON)),
    };
}

export function ChampionsToJSON(value?: Champions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'champions': value.champions === undefined ? undefined : ((value.champions as Array<any>).map(ChampionToJSON)),
    };
}

