/* tslint:disable */
/* eslint-disable */
/**
 * Clash Bot Service
 * # Welcome to Clash Bot!   Where all of your League of Legends Clash scheduling needs are met!  ## Purpose  Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.  ## Disclaimer  Clash-Bot is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or  anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games  are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A wrapper for the request body to be used in the API
 * @export
 * @interface RequestWrapper
 */
export interface RequestWrapper {
    /**
     * The unique identifier for the request
     * @type {string}
     * @memberof RequestWrapper
     */
    uuid?: string;
    /**
     * The request body
     * @type {{ [key: string]: any; }}
     * @memberof RequestWrapper
     */
    body?: { [key: string]: any; };
}

/**
 * Check if a given object implements the RequestWrapper interface.
 */
export function instanceOfRequestWrapper(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestWrapperFromJSON(json: any): RequestWrapper {
    return RequestWrapperFromJSONTyped(json, false);
}

export function RequestWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestWrapper {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'body': !exists(json, 'body') ? undefined : json['body'],
    };
}

export function RequestWrapperToJSON(value?: RequestWrapper | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'body': value.body,
    };
}

