/* tslint:disable */
/* eslint-disable */
/**
 * Clash Bot Service
 * # Welcome to Clash Bot!   Where all of your League of Legends Clash scheduling needs are met!  ## Purpose  Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.  ## Disclaimer  Clash-Bot is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or  anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games  are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Server } from './Server';
import {
    ServerFromJSON,
    ServerFromJSONTyped,
    ServerToJSON,
} from './Server';

/**
 * A list of the Player's selected Server
 * @export
 * @interface Servers
 */
export interface Servers {
    /**
     * 
     * @type {Array<Server>}
     * @memberof Servers
     */
    servers?: Array<Server>;
}

/**
 * Check if a given object implements the Servers interface.
 */
export function instanceOfServers(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ServersFromJSON(json: any): Servers {
    return ServersFromJSONTyped(json, false);
}

export function ServersFromJSONTyped(json: any, ignoreDiscriminator: boolean): Servers {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'servers': !exists(json, 'servers') ? undefined : ((json['servers'] as Array<any>).map(ServerFromJSON)),
    };
}

export function ServersToJSON(value?: Servers | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'servers': value.servers === undefined ? undefined : ((value.servers as Array<any>).map(ServerToJSON)),
    };
}

