/* tslint:disable */
/* eslint-disable */
/**
 * Clash Bot Service
 * # Welcome to Clash Bot!   Where all of your League of Legends Clash scheduling needs are met!  ## Purpose  Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.  ## Disclaimer  Clash-Bot is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or  anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games  are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Team } from './Team';
import {
    TeamFromJSON,
    TeamFromJSONTyped,
    TeamToJSON,
} from './Team';

/**
 * A list of League of Legend's Clash Teams
 * @export
 * @interface Teams
 */
export interface Teams {
    /**
     * 
     * @type {number}
     * @memberof Teams
     */
    count?: number;
    /**
     * 
     * @type {Array<Team>}
     * @memberof Teams
     */
    teams?: Array<Team>;
}

/**
 * Check if a given object implements the Teams interface.
 */
export function instanceOfTeams(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeamsFromJSON(json: any): Teams {
    return TeamsFromJSONTyped(json, false);
}

export function TeamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Teams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'teams': !exists(json, 'teams') ? undefined : ((json['teams'] as Array<any>).map(TeamFromJSON)),
    };
}

export function TeamsToJSON(value?: Teams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'teams': value.teams === undefined ? undefined : ((value.teams as Array<any>).map(TeamToJSON)),
    };
}

