/* tslint:disable */
/* eslint-disable */
/**
 * Clash Bot Service
 * # Welcome to Clash Bot!   Where all of your League of Legends Clash scheduling needs are met!  ## Purpose  Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.  ## Disclaimer  Clash-Bot is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or  anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games  are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Role } from './Role';
import {
    RoleFromJSON,
    RoleFromJSONTyped,
    RoleToJSON,
} from './Role';

/**
 * Details necessary to update a User's position on a Team based on fluid details.
 * @export
 * @interface TeamTournamentDetails
 */
export interface TeamTournamentDetails {
    /**
     * The user's Discord Id.
     * @type {string}
     * @memberof TeamTournamentDetails
     */
    discordId?: string;
    /**
     * The Clash Tournament's name.
     * @type {any}
     * @memberof TeamTournamentDetails
     */
    tournamentName?: any | null;
    /**
     * The Clash Tournament's day.
     * @type {any}
     * @memberof TeamTournamentDetails
     */
    tournamentDay?: any | null;
    /**
     * 
     * @type {Role}
     * @memberof TeamTournamentDetails
     */
    role?: Role;
}

/**
 * Check if a given object implements the TeamTournamentDetails interface.
 */
export function instanceOfTeamTournamentDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeamTournamentDetailsFromJSON(json: any): TeamTournamentDetails {
    return TeamTournamentDetailsFromJSONTyped(json, false);
}

export function TeamTournamentDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamTournamentDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'discordId': !exists(json, 'discordId') ? undefined : json['discordId'],
        'tournamentName': !exists(json, 'tournamentName') ? undefined : json['tournamentName'],
        'tournamentDay': !exists(json, 'tournamentDay') ? undefined : json['tournamentDay'],
        'role': !exists(json, 'role') ? undefined : RoleFromJSON(json['role']),
    };
}

export function TeamTournamentDetailsToJSON(value?: TeamTournamentDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'discordId': value.discordId,
        'tournamentName': value.tournamentName,
        'tournamentDay': value.tournamentDay,
        'role': RoleToJSON(value.role),
    };
}

