/* tslint:disable */
/* eslint-disable */
/**
 * Clash Bot Service
 * # Welcome to Clash Bot!   Where all of your League of Legends Clash scheduling needs are met!  ## Purpose  Clash Bot Webapp Service to support League of Legends Clash tournament scheduling with Discord.  ## Disclaimer  Clash-Bot is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or  anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games  are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: rixxroid@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Allowed properties to be updated on a Clash Team
 * @export
 * @interface TeamUpdate
 */
export interface TeamUpdate {
    /**
     * The name of the team
     * @type {string}
     * @memberof TeamUpdate
     */
    teamName: string;
}

/**
 * Check if a given object implements the TeamUpdate interface.
 */
export function instanceOfTeamUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "teamName" in value;

    return isInstance;
}

export function TeamUpdateFromJSON(json: any): TeamUpdate {
    return TeamUpdateFromJSONTyped(json, false);
}

export function TeamUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'teamName': json['teamName'],
    };
}

export function TeamUpdateToJSON(value?: TeamUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'teamName': value.teamName,
    };
}

